const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    
    // Changed to 'items' to match your Checkout/ShopContext logic
    items: [
        {
            product: {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'Product',
                required: true
            },
            // Metadata for mattress specific details
            productName: { type: String, required: true },
            imageUrl: { type: String, required: true },
            quantity: { type: Number, required: true, default: 1 },
            price: { type: Number, required: true },
            length: { type: Number, required: true },
            width: { type: Number, required: true },
            thickness: { type: String, required: true },
            sizeCategory: { type: String }, 
            isCustom: { type: Boolean, default: false }
        }
    ],

    // Renamed to shippingDetails to match your frontend API call
    shippingDetails: {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },
        email: { type: String, required: true },
        address: { type: String, required: true },
        city: { type: String, required: true },
        state: { type: String, required: true },
        zip: { type: String, required: true }, // Changed pincode to zip
        phone: { type: String, required: true } // Changed phoneNo to phone
    },

    paymentInfo: {
        razorpay_payment_id: { type: String }, // Provided after payment success
        razorpay_order_id: { type: String },   // Generated by backend before modal opens
        razorpay_signature: { type: String },  // Required for verification
        status: { 
            type: String, 
            enum: ['Pending', 'Paid', 'Failed'], 
            default: 'Pending' 
        },
        method: { type: String, default: 'Razorpay' }
    },

    totalAmount: { type: Number, required: true, default: 0 },

    orderStatus: {
        type: String,
        required: true,
        enum: ['Processing', 'Shipped', 'Delivered', 'Cancelled'],
        default: 'Processing'
    },
    
    paidAt: Date,
    deliveredAt: Date,
    cancelledAt: Date
}, { timestamps: true });

module.exports = mongoose.model('Order', orderSchema);